blank_issues_enabled: true
contact_links:
  - name: ViaVersion Discord
    url: https://discord.gg/viaversion
    about: it is recommended to ask questions here. if you dont have discord account for it, you can still use blank issues. (NOT RECOMMENDED)
