name: Bug Report
description: File a bug report.
title: "[BUG]: "
assignees:
  - Lenni0451
  - RK_01
body:
  - type: markdown
    attributes:
      value: |
        **Before reporting a bug, please see if using master/dev builds from https://ci.viaversion.com/ fixes your issue.**
        Whenever you see fit, you can upload images or videos to any of the text fields.

  - type: input
    attributes:
      label: "`/viaversion dump` Output"
      description: |
        Run `/viaversion dump` in the console or in the chat, then copy and paste the given link here.
      placeholder: |
        https://dump.viaversion.com/...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Server/Client Error
      description: |
        If you encounter warnings/errors in your console, **paste them with https://mclo.gs/ and put the paste link here**.
        If the error is small/less than 10 lines, you may put it directly into this field.
        **Important**: If you are kicked for `Network Protocol Error` or an encoder/decoder exception, please click the `Open Report Directory` button on your client and paste the newest disconnect file contents.
      value: |
        ```
        Put the mclo.gs link or text here.
        ```
      placeholder: Please do not remove the grave accents; simply replace the line of text in the middle.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug Description
      description: |
        Describe the unexpected behavior.
        If you want to attach screenshots, use the comment field at the bottom of the page.
      placeholder: |
        Example: "i cannot login properly."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        List the steps on how we can reproduce the issue. Make sure we can easily understand what you mean with each step.
      placeholder: |
        Example:
        1. Login with a 1.21.1 Client as a b1.7-b1.7.3
        2. see the error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        Describe what exactly you expected to happen.
      placeholder: |
        Example: "i should log on properly."
    validations:
      required: true
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: "Checklist"
      options:
        - label: I have included a ViaVersion dump.
          required: true
        - label: I have overrided the latest build(s) from https://ci.viaversion.com/ on ViaLoader and the issue still persists.
          required: true
        - label: I have agreed that i am using my own ViaProxy, Not someone's ViaProxy Instance.
          required: true
